name: Build Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: install dependencies api
        working-directory: /Videoupload/VideoUploadApi
        run: dotnet restore 

      - name: Build api
        working-directory: /Videoupload/VideoUploadApi
        run: dotnet build    --configuration Release --no-restore

      - name: install dependencies web
        working-directory: /Videoupload/Videoupload
        run: dotnet restore 

      - name: Build web
        working-directory: /Videoupload/Videoupload
        run: dotnet build  --configuration Release --no-restore
