name: Build Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: install dependencies api
        run: dotnet restore ./hwvideoupload/Videoupload/VideoUploadApi.csproj

      - name: Build api
        run: dotnet build ./hwvideoupload/Videoupload/VideoUploadApi.csproj  --configuration Release --no-restore

      - name: install dependencies web
        run: dotnet restore ./hwvideoupload/Videoupload/Videoupload/Videoupload.csproj

      - name: Build web
        run: dotnet build ./hwvideoupload/Videoupload/Videoupload/Videoupload.csproj --configuration Release --no-restore
